name: Graphisk
author: LimeGlass
description: A Skript addon for Holograms.
version: @version@
api-version: 1.13
main: me.limeglass.graphisk.Graphisk
depend: [Skript]
softdepend: [HolographicDisplays, Holograms, DecentHolograms]